name: Create RC Pre-release

on:
  push:
    branches:
      - staging # Trigger on pushes to staging branch for RC pre-releases

permissions:
  contents: write # Needed for create-pull-request to push branch, semantic-release to create tags/releases
  issues: write # Optional for semantic-release plugins
  pull-requests: write # Needed for create-pull-request
  id-token: write # Needed for OIDC if used for publishing

jobs:
  release:
    name: Prepare and Publish RC Pre-release
    runs-on: ubuntu-latest
    # Prevent workflow run on PRs created by this workflow or commits made by semantic-release (tagging)
    if: |
      !contains(github.event.head_commit.message, 'chore(release):') &&
      github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for semantic-release commit analysis
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10
          run_install: true

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test

      # Run semantic-release: Updates package.json/changelog locally, creates tag & GitHub release notes
      - name: Semantic Release (Prep RC Pre-release)
        id: semantic
        env:
          # Use default token for creating tags/releases, as it has contents: write
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm semantic-release

      # Read the full pre-release version (e.g., 1.2.3-rc.1) from the locally modified package.json
      - name: Read Full Version from package.json
        id: read_full_version
        # Only proceed if semantic-release indicates a release was prepared
        # Check semantic-release output/exit code if possible, or just assume it modified if step succeeded
        # A simple check is to see if package.json was modified
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      # Create a Pull Request with the version bump changes
      - name: Create Pull Request for RC Version Bump
        uses: peter-evans/create-pull-request@v6
        # Only run if a version was determined
        if: steps.read_full_version.outputs.version != ''
        with:
          # Use default token, granted pull-requests: write permission
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: |
            chore(release): Update package.json and CHANGELOG.md for pre-release ${{ steps.read_full_version.outputs.version }}

            [skip ci]
          title: |
            chore(release): Updates for pre-release ${{ steps.read_full_version.outputs.version }}
          body: |
            Automated updates for pre-release version ${{ steps.read_full_version.outputs.version }}.

            Includes:
            - Version bump in `package.json`
            - Updated `CHANGELOG.md`

            This PR is automatically generated by the pre-release workflow. Please review and merge.
          branch: chore/release-${{ steps.read_full_version.outputs.version }} # Unique branch per version
          base: staging # Target branch for the PR
          delete-branch: true # Clean up the branch after merging
          add-paths: | # Explicitly add only these files from the workspace
            package.json
            CHANGELOG.md

      # === Steps for Marketplace Publication (using base version) ===

      # Calculate the base version (e.g., 1.2.3) by stripping the suffix
      - name: Calculate Base Version
        id: get_base_version
        if: steps.read_full_version.outputs.version != ''
        run: |
          full_version="${{ steps.read_full_version.outputs.version }}"
          base_version="${full_version%%-*}" # Remove shortest suffix starting with '-'
          echo "base_version=$base_version" >> $GITHUB_OUTPUT
          echo "Calculated base version: $base_version from $full_version"

      # Update package.json in the runner FS to the base version for packaging/publishing
      - name: Set package.json to Base Version (for Marketplace)
        if: steps.get_base_version.outputs.base_version != ''
        run: pnpm version ${{ steps.get_base_version.outputs.base_version }} --no-git-tag-version

      # Package the extension using the base version in package.json
      - name: Package Extension
        if: steps.get_base_version.outputs.base_version != ''
        run: pnpm package

      # Upload the VSIX asset to the GitHub release created by semantic-release
      - name: Upload VSIX to GitHub Release
        if: steps.read_full_version.outputs.version != ''
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.read_full_version.outputs.version }} # Use the actual tag created by semantic-release
          files: |
            *.vsix
          fail_on_unmatched_files: true
          prerelease: true # Ensure it targets the pre-release

      # Publish to marketplace last, using the base version but marking as pre-release
      - name: Publish RC Pre-release to Visual Studio Marketplace
        if: steps.get_base_version.outputs.base_version != ''
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.VSCE_PAT }}
          registryUrl: https://marketplace.visualstudio.com
          preRelease: true # Mark this as a pre-release on the marketplace
